### PR TITLE
Install win_iconv-devel WinRPM

### PR DESCRIPTION
**Pull request by nalimilan**
This is the package which contains the library.

### CODE REVIEW

**Comment by nalimilan** [comment]
Actually the RPM package doesn't contain the DLL at all, it needs to be improved.

**Comment by tkelman** [comment]
Looks like they moved it to a `-dll` subpackage: https://build.opensuse.org/package/rdiff/windows:mingw:win64/mingw64-win_iconv?linkrev=base&rev=14

The maintainers there are pretty good about accepting change requests. To see when a request will get published, you can watch at https://build.opensuse.org/project/monitor/windows:mingw:win64 and follow the icons at the top - the little truck means published.

**Comment by nalimilan** [comment]
Actually, I requested them to ship that DLL, and indeed they are quite responsive. win_icon is also actively maintained upstream, I just got a patch merged and a new release including it.

**Comment by tkelman** [comment]
Cross compilation, such a useful tool.

**Pull request closed without merging**
